apiVersion: v1
kind: Service
metadata:
  name: devportal-es-svc
  labels:
    app: devportal-es
spec:
  ports:
    - name: http
      port: 9200
      protocol: TCP
      targetPort: 9200
    - name: transport
      port: 9300
      protocol: TCP
      targetPort: 9300
  publishNotReadyAddresses: true
  selector:
    app: devportal-es
  sessionAffinity: None
  type: ClusterIP